---
apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>Landing Page</title>
        <script>
          function redirectTo(url) {
            window.location.href = url;
          }
          function connect(sessionFieldId, baseUrl) {
            var session = document.getElementById(sessionFieldId).value;
            if (!baseUrl.endsWith('/')) {
              baseUrl += '/';
            }
            window.location.href = baseUrl + encodeURIComponent(session);
          }
        </script>
      </head>
      <body>
        <h1>Sumplete</h1>
        <button onclick="redirectTo('https://pmqxyz.hopto.org/sumplete/')">Sumplete elérése</button>
        <input type="text" id="sumplete-session" placeholder="Session">
        <button onclick="connect('sumplete-session', 'https://pmqxyz.hopto.org/sumplete/')">Csatlakozás</button>

        <h1>Ultimate Tic Tac Toe</h1>
        <button onclick="redirectTo('https://pmqxyz.hopto.org/tic-tac-toe/')">Ultimate Tic Tac Toe elérése</button>
        <input type="text" id="ttt-session" placeholder="Session">
        <button onclick="connect('ttt-session', 'https://pmqxyz.hopto.org/tic-tac-toe/')">Csatlakozás</button>

        <h1>Sakk</h1>
        <button onclick="redirectTo('https://pmqxyz.hopto.org/chess/')">Sakk elérése</button>
        <input type="text" id="chess-session" placeholder="Session">
        <button onclick="connect('chess-session', 'https://pmqxyz.hopto.org/chess/')">Csatlakozás</button>

        <h1>Sudoku</h1>
        <button onclick="redirectTo('https://pmqxyz.hopto.org/sudoku/')">Sudoku elérése</button>

        <h1>Bakos emlékverseny</h1>
        <button onclick="redirectTo('https://pmqxyz.hopto.org/bakos/')">Bakos emlékverseny elérése</button>


        <h1>Maffia</h1>
        <button onclick="redirectTo('https://pmqxyz.hopto.org/maffia/')">Maffia elérése</button>

      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-deployment
  labels:
    app: landing-page
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: landing-page-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: landing-page-volume
        configMap:
          name: landing-page
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
spec:
  selector:
    app: landing-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
